Repository carvel-dev/kapp-controller, pull requests merged in 2022-12, with the labels that each got.

#994 Bump cobrautil in cli
  cli/cmd/kctrl/kctrl.go
  cli/go.mod
  cli/go.sum
  cli/vendor/github.com/cppforlife/cobrautil/help_sections.go
  cli/vendor/github.com/cppforlife/cobrautil/misc.go
  cli/vendor/modules.txt
Labels: cla-not-required

#993 Add space for if condition in trivy-scan
  .github/workflows/trivy-scan.yml
Labels: cla-not-required

#999 Set seccompProfile type for both containers
  config/deployment.yml
Labels: cla-not-required

#1014 bump golang version to 1.19.3
  Dockerfile
Labels: cla-not-required

#1008 Bump dependencies to latest patches
  go.mod
  go.sum
  hack/dependencies.yml
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/modules.txt
Labels: cla-not-required, v0.43.x

#1017 Bump golang to 1.19.3
  .github/workflows/benchmark-action.yaml
  .github/workflows/dependency-updater.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/kind-action.yml
  .github/workflows/release-process.yml
  .github/workflows/test-gh.yml
  .github/workflows/test-kctrl-gh.yml
  .github/workflows/trivy-scan.yml
  .github/workflows/upgrade-testing.yml
  Dockerfile
Labels: cla-not-required, v0.41.x

#1016 Bump golang to 1.19.3
  Dockerfile
Labels: cla-not-required, v0.38.x

#1015 Bump golang to 1.19.3
  .github/workflows/benchmark-action.yaml
  .github/workflows/dependency-updater.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/kind-action.yml
  .github/workflows/release-process.yml
  .github/workflows/test-gh.yml
  .github/workflows/test-kctrl-gh.yml
  .github/workflows/trivy-scan.yml
  .github/workflows/upgrade-testing.yml
  Dockerfile
Labels: cla-not-required, v0.43.x

#1019 Install imgpkg before running release workflow (#986)
  .github/workflows/release-process.yml
Labels: cla-not-required

#1025 Update secure namespace flag name in a hint
  cli/pkg/kctrl/cmd/core/secure_namespace_flags.go
Labels: cla-not-required

#1026 Bump golang.org/x/net in cli
  cli/go.mod
  cli/go.sum
  cli/vendor/golang.org/x/net/http2/hpack/encode.go
  cli/vendor/golang.org/x/net/http2/server.go
  cli/vendor/golang.org/x/net/http2/transport.go
  cli/vendor/golang.org/x/sys/windows/syscall_windows.go
  cli/vendor/golang.org/x/sys/windows/zsyscall_windows.go
  cli/vendor/golang.org/x/text/unicode/bidi/trieval.go
  cli/vendor/modules.txt
Labels: cla-not-required

#1024 Bump go 1.19.3
  .github/workflows/benchmark-action.yaml
  .github/workflows/dependency-updater.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/kind-action.yml
  .github/workflows/release-process.yml
  .github/workflows/test-gh.yml
  .github/workflows/test-kctrl-gh.yml
  .github/workflows/trivy-scan.yml
  .github/workflows/upgrade-testing.yml
  .golangci.yml
  Dockerfile
  cmd/controller/err_reconciler.go
  hack/dependencies.go
  pkg/componentinfo/component_info.go
  pkg/config/config.go
  pkg/kubeconfig/kubeconfig.go
  pkg/satoken/token_manager.go
  pkg/sidecarexec/client.go
  pkg/template/cue.go
Labels: cla-not-required

#991 Remove file path on automated release note generated
  .github/workflows/release-process.yml
  hack/build-release.sh
Labels: cla-not-required

#1013 Fix app status diff, to ensure that deploy output is deduped
  cli/pkg/kctrl/cmd/app/app_tailer.go
  cli/pkg/kctrl/cmd/package/repository/repo_tailer.go
  cli/test/e2e/package_install_test.go
Labels: cla-not-required

#989 Do not run/stop workflows that are not required
  .github/workflows/kind-action.yml
  .github/workflows/test-gh.yml
  .github/workflows/test-kctrl-gh.yml
  .github/workflows/upgrade-testing.yml
Labels: cla-not-required

#1033 Bump testing redis chart to latest [17.3.17]
  examples/redis-helm.yml
  test/e2e/kappcontroller/helm_test.go
Labels: cla-not-required

#1030 Fix warning in trivy scan and add error check to the command
  .github/workflows/trivy-scan.yml
Labels: cla-not-required
